torch_seed: 101
verbose: True
model_settings:
  model_class: resnet50_conv3
  num_labels: 8 #num colors (will correct for position)
  latent_dim: 128
  model_path: /home/lmeyers/ReID_complete/summer_color_detect.pth
train_settings:
  learning_rate: 0.001
  num_epochs: 1500
  margin: 0.2
  pos_weight: 5
  print_k: 10
  save_checkpoint_freq: 100
  gpu: 0
  wandb_project_name: color_detect_summer_data
  wandb_entity_name: meyers_luke_lab
  wandb_resume: False
  checkpoint_to_load: #if resuming
  wandb_run_id: #if resuming
data_settings:
  dataset: summer_2023
  split_type: closed
  fname_col: filename
  label_col: color_num
  cropped: False
  crop_top:
  crop_left:
  crop_height:
  crop_width:
  input_size: [250, 250]
  batch_size: 64
  aug_p: .3
  datafiles:
    train: /home/lmeyers/ReID_complete/summer_2023_reid_train_closed.csv
    valid: /home/lmeyers/ReID_complete/summer_2023_reid_valid_closed.csv
    test: /home/lmeyers/ReID_complete/summer_2023_reid_test_closed.csv
    reference: /home/lmeyers/ReID_complete/summer_2023_reid_train_closed.csv
    query: /home/lmeyers/ReID_complete/summer_2023_reid_test_closed.csv
    gallery: /home/lmeyers/ReID_complete/summer_2023_reid_galleries_closed.csv
    color_map: /home/lmeyers/ReID_complete/summer_2023_v3_color_map_w_order.json
  n_distractors: 9
  image_id_col: image_id
  gallery_id: gallery_id
  iteration_id: iteration_id
eval_settings:
  n_neighbors: 3
  per_class: True
  conf_matrix: True